fix: dot-notation now respects strip-dashed
yargs/yargs-parser pull request #288
Opened 2020-06-26 21:15 UTC by Mike111177

Fixes #261

2020-06-27 16:11 UTC, Mike111177 commented
Actually, just realized, this may infinitely a circular reference into a coerced arg.... fix pending....

2020-06-27 17:35 UTC, Mike111177 commented
Fixed, ready

2020-07-18 22:12 UTC, bcoe commented
Hey @Mike111177 sorry for the slow reply. Bother you to rebase against the main branch, I've been working on landing some of our TypeScript work.

2020-08-11 01:20 UTC, bcoe commented
@Mike111177 just a friendly note, to ask whether this is still something you'd like to see landed.

2020-08-11 21:39 UTC, Mike111177 commented
Completely forgot about it lol, here you go.

2020-08-11 21:49 UTC, Mike111177 commented
thats odd, im not getting the standardx error when i run it locally...

2020-08-27 04:35 UTC, bcoe commented
@Mike111177 I owe you review, haven't forgotten about this myself.

2020-09-20 04:14 UTC, bcoe requested changes
This looks like a good fix to me 👍 could I bother you to rebase and fix the one nit?

2020-09-20 04:14 UTC, bcoe commented on lib/yargs-parser.ts
> +            var obj = argv
can this be a `let`?

2020-09-20 20:30 UTC, bcoe commented on lib/yargs-parser.ts
> +            var obj = argv
```suggestion
            let obj = argv
```

2020-09-20 20:30 UTC, bcoe commented on test/yargs-parser.cjs
> +      var argv = parser(['--dashed-will-be-stripped', '--here.it-will-too',
```suggestion
      const argv = parser(['--dashed-will-be-stripped', '--here.it-will-too',
```

2020-09-20 20:30 UTC, bcoe commented on test/yargs-parser.cjs
> +      var argv = parser(['--foo.not-dashed'], {
```suggestion
      const argv = parser(['--foo.not-dashed'], {
```

2020-09-20 20:32 UTC, bcoe approved these changes

2020-09-20 21:08 UTC, bcoe commented
@@Mike111177 shoot, with my rebase I seem to now be in a position where tests aren't passing.

2020-10-14 18:38 UTC, bcoe requested changes
Sorry for being so slow with review on this issue, I've been a little bit swamped.

The reason I didn't land immediately, is that I'm a little concerned about adding so much logic related to handling a single config variation for dot-notation.

Could we figure out a way to pull the dot-notation check into a helper function perhaps that we could reuse to make dot notation respect configuration in a more general sense? I feel like there are many config settings that dot notation doesn't respect.

2021-02-15 22:30 UTC, bcoe commented
@Mike111177 just checking if you still want to land this.

2021-03-05 22:46 UTC, closed without merging

2021-03-05 22:46 UTC, bcoe commented
@Mike111177 let me know when/if you would like to dust this off 👍